import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { DecimalPipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { ButtonModule } from 'primeng/button';
import { SelectModule } from 'primeng/select';
import { Product } from '../../core/models/domain.models';
import { ProductService } from '../../core/services/product.service';
import { ImageFallbackDirective } from '../../shared/directives/image-fallback.directive';
import { ErrorStateComponent } from '../../shared/components/error-state.component';
import { LoadingStateComponent } from '../../shared/components/loading-state.component';

@Component({ selector: 'app-catalog', standalone: true, imports: [FormsModule, RouterLink, ButtonModule, SelectModule, DecimalPipe, ImageFallbackDirective, ErrorStateComponent, LoadingStateComponent], changeDetection: ChangeDetectionStrategy.OnPush, template: `<section class="catalog-page"><div class="catalog-hero"><div><div class="eyebrow">Le catalogue Solaris</div><h1>Des composants qui<br /><em>font la différence.</em></h1><p>Des milliers de références sélectionnées pour des installations fiables, performantes et durables.</p></div><div class="catalog-hero-art"><i class="pi pi-sun"></i><span>Énergie<br />pour demain</span></div></div><div class="catalog-toolbar"><div class="catalog-search"><i class="pi pi-search"></i><input [(ngModel)]="search" (ngModelChange)="loadProducts()" placeholder="Rechercher un produit, une référence..." /></div><div class="category-pills"><button [class.active]="category === ''" (click)="setCategory('')">Tous <span>{{ products().length }}</span></button>@for (item of categories; track item.value) { <button [class.active]="category === item.value" (click)="setCategory(item.value)">{{ item.label }}</button> }</div><p-select [options]="sortOptions" [(ngModel)]="sort" optionLabel="label" optionValue="value" placeholder="Trier par" /></div><div class="catalog-meta"><span><strong>{{ products().length }}</strong> produits disponibles</span><span class="catalog-view"><button class="active"><i class="pi pi-th-large"></i></button><button><i class="pi pi-list"></i></button></span></div>@if (loading()) { <app-loading-state message="Chargement du catalogue..." /> } @else if (error()) { <app-error-state (retry)="loadProducts()" /> } @else { <div class="product-grid">@for (product of products(); track product.id) { <article class="product-card"><a [routerLink]="['/catalogue', product.id]" class="product-image"><img [src]="product.image" appImageFallback [alt]="product.name" /><span class="product-category">{{ product.categoryLabel }}</span><button class="product-favorite" aria-label="Ajouter aux favoris"><i class="pi pi-heart"></i></button></a><div class="product-info"><div class="product-brand">{{ product.brand }} <span>· {{ product.reference }}</span></div><h3><a [routerLink]="['/catalogue', product.id]">{{ product.name }}</a></h3><div class="product-bottom"><strong>{{ product.price | number:'1.2-2' }} €</strong><span class="stock-status" [class.low]="product.stock < 10" [class.out]="product.stock === 0"><i class="pi pi-circle-fill"></i>{{ product.stock === 0 ? 'Rupture' : product.stock < 10 ? 'Stock faible' : 'En stock' }}</span></div></div></article> } @empty { <div class="catalog-empty"><i class="pi pi-search"></i><h3>Aucun produit trouvé</h3><p>Essayez avec d’autres mots-clés ou catégories.</p></div> }</div> }</section>` })
export class CatalogComponent {
  private readonly productService = inject(ProductService); products = signal<Product[]>([]); loading = signal(true); error = signal(false); search = ''; category = ''; sort = 'featured';
  categories = [{ label: 'Panneaux', value: 'PANELS' }, { label: 'Batteries', value: 'BATTERIES' }, { label: 'Onduleurs', value: 'INVERTERS' }, { label: 'Accessoires', value: 'ACCESSORIES' }]; sortOptions = [{ label: 'Recommandés', value: 'featured' }, { label: 'Prix croissant', value: 'priceAsc' }, { label: 'Prix décroissant', value: 'priceDesc' }];
  constructor() { this.loadProducts(); }
  loadProducts(): void { this.loading.set(true); this.error.set(false); this.productService.getProducts({ search: this.search, category: this.category }).subscribe({ next: (items) => { const sorted = [...items].sort((a, b) => this.sort === 'priceAsc' ? a.price - b.price : this.sort === 'priceDesc' ? b.price - a.price : 0); this.products.set(sorted); this.loading.set(false); }, error: () => { this.error.set(true); this.loading.set(false); } }); }
  setCategory(category: string): void { this.category = category; this.loadProducts(); }
}
