import { AsyncPipe, CurrencyPipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { ButtonModule } from 'primeng/button';
import { ProductService } from '../../core/services/product.service';
import { ImageFallbackDirective } from '../../shared/directives/image-fallback.directive';

@Component({ selector: 'app-product-detail', standalone: true, imports: [AsyncPipe, CurrencyPipe, RouterLink, ButtonModule, ImageFallbackDirective], changeDetection: ChangeDetectionStrategy.OnPush, template: `@if (product$ | async; as product) { <section class="detail-page"><a class="back-link" routerLink="/catalogue"><i class="pi pi-arrow-left"></i> Retour au catalogue</a><div class="detail-layout"><div class="detail-gallery"><div class="detail-main-image"><img appImageFallback [src]="product.image" [alt]="product.name" /></div><div class="detail-thumb active"><img appImageFallback [src]="product.image" [alt]="product.name" /></div></div><div class="detail-content"><div class="product-brand">{{ product.brand }} <span>· {{ product.reference }}</span></div><h1>{{ product.name }}</h1><p class="detail-description">{{ product.description }}</p><div class="detail-price">{{ product.price | currency:'EUR':'symbol':'1.2-2':'fr' }} <span>HT</span></div><div class="availability"><i class="pi pi-check-circle"></i><div><strong>Disponible</strong><span>Expédition sous 2 à 4 jours ouvrés</span></div></div><div class="detail-actions"><p-button label="Demander un devis" icon="pi pi-file-edit" /><button class="outline-button"><i class="pi pi-heart"></i></button></div><div class="detail-meta"><div><span>Catégorie</span><strong>{{ product.categoryLabel }}</strong></div><div><span>Distributeur</span><strong>{{ product.distributor }}</strong></div><div><span>Garantie</span><strong>{{ product.specs[3].value }}</strong></div></div></div></div><div class="specs-section"><div class="eyebrow">Fiche technique</div><h2>Les détails qui comptent.</h2><div class="specs-grid">@for (spec of product.specs; track spec.label) { <div><span>{{ spec.label }}</span><strong>{{ spec.value }}</strong></div> }</div></div></section> } @else { <div class="detail-loading">Chargement du produit...</div> }` })
export class ProductDetailComponent { private readonly route = inject(ActivatedRoute); private readonly productService = inject(ProductService); product$ = this.productService.getProductById(this.route.snapshot.paramMap.get('id') ?? ''); }
