import { CurrencyPipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';
import { Product } from '../../core/models/domain.models';
import { ProductService } from '../../core/services/product.service';
import { PageHeaderComponent } from '../../shared/components/page-header.component';
import { EmptyStateComponent } from '../../shared/components/empty-state.component';
import { ImageFallbackDirective } from '../../shared/directives/image-fallback.directive';
import { LoadingStateComponent } from '../../shared/components/loading-state.component';

@Component({ selector: 'app-product-list', standalone: true, imports: [CurrencyPipe, FormsModule, ButtonModule, InputTextModule, PageHeaderComponent, EmptyStateComponent, ImageFallbackDirective, LoadingStateComponent], changeDetection: ChangeDetectionStrategy.OnPush, template: `<app-page-header eyebrow="Gestion du catalogue" title="Produits" subtitle="Gérez votre catalogue, vos stocks et vos références."><p-button label="Ajouter un produit" icon="pi pi-plus" /></app-page-header><div class="list-toolbar"><div class="catalog-search"><i class="pi pi-search"></i><input pInputText [(ngModel)]="search" (ngModelChange)="load()" placeholder="Rechercher par nom ou référence..." /></div><button class="filter-button"><i class="pi pi-sliders-h"></i> Filtres <span>2</span></button><button class="filter-button"><i class="pi pi-download"></i> Exporter</button></div>@if (loading()) { <app-loading-state message="Chargement des produits..." /> } @else { <div class="table-container"><div class="table-title"><div><strong>Catalogue produits</strong><span>{{ products().length }} références</span></div><div class="table-tabs"><button class="active">Tous</button><button>Actifs</button><button>Stock faible</button></div></div>@if (products().length) { <div class="product-admin-table"><div class="admin-row admin-head"><span>Produit</span><span>Catégorie</span><span>Prix unitaire</span><span>Stock</span><span>Statut</span><span></span></div>@for (product of products(); track product.id) { <div class="admin-row"><div class="admin-product"><img appImageFallback [src]="product.image" [alt]="product.name" /><div><strong>{{ product.name }}</strong><small>{{ product.reference }} · {{ product.brand }}</small></div></div><span>{{ product.categoryLabel }}</span><strong>{{ product.price | currency:'EUR':'symbol':'1.2-2':'fr' }}</strong><span [class.stock-low]="product.stock < 10">{{ product.stock }} unités</span><span class="status-pill" [class.active]="product.status === 'ACTIVE'" [class.low]="product.status === 'LOW_STOCK'" [class.draft]="product.status === 'DRAFT'"><i class="pi pi-circle-fill"></i>{{ product.status === 'ACTIVE' ? 'Actif' : product.status === 'LOW_STOCK' ? 'Stock faible' : 'Brouillon' }}</span><button class="row-menu" aria-label="Actions"><i class="pi pi-ellipsis-h"></i></button></div> }</div> } @else { <app-empty-state title="Aucun produit trouvé" message="Votre recherche ne correspond à aucune référence." /> }</div> }` })
export class ProductListComponent { private readonly productService = inject(ProductService); products = signal<Product[]>([]); loading = signal(true); search = ''; constructor() { this.load(); } load(): void { this.loading.set(true); this.productService.getProducts({ search: this.search }).subscribe((items) => { this.products.set(items); this.loading.set(false); }); } }
