import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { delay } from 'rxjs/operators';
import { WorkspaceConfig, WorkspaceKind } from '../models/workspace.models';

const workspaceData: Record<WorkspaceKind, WorkspaceConfig> = {
  orders: { kind: 'orders', eyebrow: 'Suivi opérationnel', title: 'Commandes', subtitle: 'Pilotez chaque commande, de la confirmation à la livraison.', actionLabel: 'Nouvelle commande', actionIcon: 'pi-plus', summary: [{ label: 'Total commandes', value: '1 248', caption: '+8,4% ce mois', tone: 'blue' }, { label: 'À préparer', value: '28', caption: 'À traiter aujourd’hui', tone: 'amber' }, { label: 'En transit', value: '64', caption: 'Livraison en cours', tone: 'teal' }, { label: 'Chiffre d’affaires', value: '284 920 €', caption: '+12,8% ce mois', tone: 'coral' }], rows: [{ id: '#CMD-1048', primary: 'Énergie du Sud', secondary: 'Panneau Aurora 450W', detail: '40 unités', status: 'Confirmée', tone: 'teal', date: 'Aujourd’hui, 09:42', icon: 'pi-shopping-bag' }, { id: '#CMD-1047', primary: 'Youssef Haddad', secondary: 'Batterie Voltis Home 10', detail: '1 unité', status: 'Préparation', tone: 'amber', date: 'Hier, 16:18', icon: 'pi-box' }, { id: '#CMD-1046', primary: 'SunTech Solutions', secondary: 'Onduleur GridOne 8K', detail: '3 unités', status: 'Expédiée', tone: 'blue', date: 'Hier, 11:03', icon: 'pi-send' }, { id: '#CMD-1045', primary: 'Amel Bensalem', secondary: 'Kit de fixation Toit Plat', detail: '10 unités', status: 'Livrée', tone: 'neutral', date: '12 juin, 14:26', icon: 'pi-check-circle' }] },
  quotes: { kind: 'quotes', eyebrow: 'Commerce', title: 'Devis', subtitle: 'Centralisez les demandes et propositions commerciales.', actionLabel: 'Créer un devis', actionIcon: 'pi-file-plus', summary: [{ label: 'Devis en cours', value: '42', caption: '12 à traiter', tone: 'blue' }, { label: 'À envoyer', value: '18', caption: 'Cette semaine', tone: 'amber' }, { label: 'Acceptés', value: '86', caption: '+16,2% ce mois', tone: 'teal' }, { label: 'Valeur estimée', value: '96 480 €', caption: 'Pipeline actif', tone: 'coral' }], rows: [{ id: '#DEV-284', primary: 'SunTech Solutions', secondary: 'Installation commerciale 24 kWc', detail: '12 lignes produit', status: 'À envoyer', tone: 'amber', date: 'Aujourd’hui, 08:20', icon: 'pi-file-edit' }, { id: '#DEV-283', primary: 'Nadia Belkacem', secondary: 'Autoconsommation résidentielle', detail: '6 lignes produit', status: 'En attente', tone: 'blue', date: 'Hier, 14:50', icon: 'pi-clock' }, { id: '#DEV-282', primary: 'Énergie du Sud', secondary: 'Extension batterie 20 kWh', detail: '4 lignes produit', status: 'Accepté', tone: 'teal', date: '12 juin, 10:12', icon: 'pi-check-circle' }] },
  installations: { kind: 'installations', eyebrow: 'Opérations terrain', title: 'Installations', subtitle: 'Suivez les installations attribuées à vos équipes.', actionLabel: 'Planifier une installation', actionIcon: 'pi-calendar-plus', summary: [{ label: 'En cours', value: '18', caption: '6 prioritaires', tone: 'blue' }, { label: 'Planifiées', value: '32', caption: 'Dans les 30 jours', tone: 'amber' }, { label: 'Terminées', value: '284', caption: '+11,5% ce mois', tone: 'teal' }, { label: 'Puissance installée', value: '32 MW', caption: 'Depuis le début', tone: 'coral' }], rows: [{ id: '#INS-1042', primary: 'Résidence Benali', secondary: '6,4 kWc résidentiel', detail: 'Installateur : Solaire Plus', status: 'En cours', tone: 'blue', date: '18 juin 2025', icon: 'pi-bolt' }, { id: '#INS-1041', primary: 'Atelier El Amal', secondary: '24 kWc commercial', detail: 'Installateur : EcoVolt', status: 'Planifiée', tone: 'amber', date: '22 juin 2025', icon: 'pi-calendar' }, { id: '#INS-1038', primary: 'Ferme Agri-Sud', secondary: '80 kWc industriel', detail: 'Installateur : GreenWorks', status: 'Terminée', tone: 'teal', date: '12 juin 2025', icon: 'pi-check-circle' }] },
  interventions: { kind: 'interventions', eyebrow: 'Support technique', title: 'Interventions', subtitle: 'Planifiez et documentez les interventions techniques.', actionLabel: 'Nouvelle intervention', actionIcon: 'pi-wrench', summary: [{ label: 'À venir', value: '12', caption: 'Les 7 prochains jours', tone: 'blue' }, { label: 'Urgentes', value: '3', caption: 'À traiter maintenant', tone: 'coral' }, { label: 'En cours', value: '8', caption: 'Techniciens mobilisés', tone: 'amber' }, { label: 'Résolues', value: '156', caption: '+9,4% ce mois', tone: 'teal' }], rows: [{ id: '#INT-884', primary: 'Résidence Benali', secondary: 'Baisse de rendement', detail: 'Technicien : Walid Saïdi', status: 'Urgente', tone: 'coral', date: 'Aujourd’hui, 13:00', icon: 'pi-exclamation-triangle' }, { id: '#INT-883', primary: 'Ferme Agri-Sud', secondary: 'Maintenance préventive', detail: 'Technicien : Amine Khelifi', status: 'Planifiée', tone: 'blue', date: '19 juin 2025', icon: 'pi-calendar' }, { id: '#INT-881', primary: 'Atelier El Amal', secondary: 'Remplacement capteur', detail: 'Technicien : Lina Haddad', status: 'En cours', tone: 'amber', date: 'Aujourd’hui, 10:30', icon: 'pi-wrench' }] },
  users: { kind: 'users', eyebrow: 'Administration', title: 'Utilisateurs', subtitle: 'Gérez les acteurs de votre écosystème.', actionLabel: 'Inviter un utilisateur', actionIcon: 'pi-user-plus', summary: [{ label: 'Total utilisateurs', value: '2 486', caption: '+12% ce mois', tone: 'blue' }, { label: 'Distributeurs', value: '184', caption: 'Partenaires actifs', tone: 'teal' }, { label: 'Installateurs', value: '426', caption: 'Réseau certifié', tone: 'amber' }, { label: 'Clients', value: '1 820', caption: 'Comptes actifs', tone: 'coral' }], rows: [{ id: 'USR-001', primary: 'Sofia Benali', secondary: 'Administrateur', detail: 'Solaris Energy', status: 'Actif', tone: 'teal', date: 'Aujourd’hui, 09:12', icon: 'pi-shield' }, { id: 'USR-248', primary: 'Karim Mansouri', secondary: 'Distributeur', detail: 'Helio Distribution', status: 'Actif', tone: 'teal', date: 'Hier, 16:22', icon: 'pi-building' }, { id: 'USR-512', primary: 'Lina Haddad', secondary: 'Technicienne', detail: 'EcoVolt', status: 'En attente', tone: 'amber', date: '12 juin 2025', icon: 'pi-user' }] },
  notifications: { kind: 'notifications', eyebrow: 'Communication', title: 'Notifications', subtitle: 'Retrouvez toutes les alertes importantes de votre activité.', actionLabel: 'Tout marquer comme lu', actionIcon: 'pi-check', summary: [{ label: 'Non lues', value: '3', caption: 'À consulter', tone: 'blue' }, { label: 'Commandes', value: '8', caption: 'Cette semaine', tone: 'teal' }, { label: 'Alertes stock', value: '4', caption: 'À surveiller', tone: 'amber' }, { label: 'Système', value: '2', caption: 'Informations', tone: 'coral' }], rows: [{ id: 'NOT-01', primary: 'Nouvelle commande reçue', secondary: 'Commande #CMD-1048 de Énergie du Sud', detail: 'Une action est requise', status: 'Non lue', tone: 'blue', date: 'Il y a 18 min', icon: 'pi-shopping-bag' }, { id: 'NOT-02', primary: 'Stock faible', secondary: 'Batterie Voltis Home 10 — 7 unités restantes', detail: 'Seuil d’alerte atteint', status: 'Non lue', tone: 'amber', date: 'Il y a 42 min', icon: 'pi-exclamation-triangle' }, { id: 'NOT-03', primary: 'Devis accepté', secondary: 'Devis #DEV-284 par SunTech Solutions', detail: 'Félicitations, votre devis a été accepté', status: 'Lue', tone: 'teal', date: 'Il y a 2 h', icon: 'pi-check-circle' }] },
  settings: { kind: 'settings', eyebrow: 'Configuration', title: 'Paramètres', subtitle: 'Personnalisez votre espace Solaris.', actionLabel: 'Enregistrer les modifications', actionIcon: 'pi-save', summary: [], rows: [] },
};

@Injectable({ providedIn: 'root' })
export class WorkspaceService {
  getWorkspace(kind: WorkspaceKind): Observable<WorkspaceConfig> { return of(workspaceData[kind]).pipe(delay(520)); }
}
