import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { Router, RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { ButtonModule } from 'primeng/button';
import { MenuModule } from 'primeng/menu';
import { AuthService } from '../../core/services/auth.service';
import { roleLabels } from '../../core/constants/permissions';

interface NavItem { label: string; icon: string; route?: string; divider?: boolean; }

@Component({ selector: 'app-dashboard-layout', standalone: true, imports: [RouterOutlet, RouterLink, RouterLinkActive, ButtonModule, MenuModule], changeDetection: ChangeDetectionStrategy.OnPush, template: `<div class="dashboard-layout"><aside class="sidebar" [class.collapsed]="collapsed()"><div class="sidebar-top"><a class="brand" routerLink="/"><span class="brand-mark"><i class="pi pi-sun"></i></span>@if (!collapsed()) { <span>solaris<span class="brand-dot">.</span></span> }</a><button class="collapse-btn" (click)="collapsed.set(!collapsed())" [attr.aria-label]="collapsed() ? 'Développer le menu' : 'Réduire le menu'"><i class="pi" [class.pi-angle-left]="!collapsed()" [class.pi-angle-right]="collapsed()"></i></button></div><div class="workspace-label">ESPACE {{ roleLabel().toUpperCase() }}</div><nav class="sidebar-nav">@for (item of navItems; track item.label) { @if (item.divider) { <div class="nav-divider"></div> } @else { <a class="sidebar-link" [routerLink]="item.route" routerLinkActive="active" [routerLinkActiveOptions]="{exact: item.route === '/app'}" [title]="collapsed() ? item.label : ''"><i class="pi {{ item.icon }}"></i>@if (!collapsed()) { <span>{{ item.label }}</span> }</a> } }</nav><div class="sidebar-bottom"><a class="sidebar-link" routerLink="/app/settings"><i class="pi pi-cog"></i>@if (!collapsed()) { <span>Paramètres</span> }</a><button class="sidebar-link logout" (click)="logout()"><i class="pi pi-sign-out"></i>@if (!collapsed()) { <span>Se déconnecter</span> }</button></div></aside><div class="dashboard-main"><header class="dashboard-header"><button class="mobile-sidebar" (click)="collapsed.set(!collapsed())" aria-label="Menu"><i class="pi pi-bars"></i></button><div class="header-search"><i class="pi pi-search"></i><input placeholder="Rechercher dans Solaris..." /></div><div class="header-actions"><button class="icon-action notification-action" aria-label="Notifications"><i class="pi pi-bell"></i><span>3</span></button><div class="header-separator"></div><button class="user-menu"><span class="avatar">{{ initials() }}</span><span class="user-meta"><strong>{{ fullName() }}</strong><small>{{ roleLabel() }}</small></span><i class="pi pi-chevron-down"></i></button></div></header><main class="dashboard-content"><router-outlet /></main></div></div>` })
export class DashboardLayoutComponent {
  private readonly auth = inject(AuthService); private readonly router = inject(Router); collapsed = signal(false);
  navItems: NavItem[] = [{ label: 'Vue d’ensemble', icon: 'pi-grid-2', route: '/app' }, { label: 'Catalogue', icon: 'pi-box', route: '/app/products' }, { label: 'Commandes', icon: 'pi-shopping-bag', route: '/app/orders' }, { label: 'Devis', icon: 'pi-file-edit', route: '/app/quotes' }, { label: 'Installations', icon: 'pi-bolt', route: '/app/installations' }, { label: 'Interventions', icon: 'pi-wrench', route: '/app/interventions' }, { label: '', icon: '', divider: true }, { label: 'Utilisateurs', icon: 'pi-users', route: '/app/users' }, { label: 'Notifications', icon: 'pi-bell', route: '/app/notifications' }];
  roleLabel = () => roleLabels[this.auth.currentUser()?.role ?? 'DISTRIBUTOR'];
  fullName = () => `${this.auth.currentUser()?.firstName ?? 'Karim'} ${this.auth.currentUser()?.lastName ?? 'Mansouri'}`;
  initials = () => `${this.auth.currentUser()?.firstName?.[0] ?? 'K'}${this.auth.currentUser()?.lastName?.[0] ?? 'M'}`;
  logout(): void { this.auth.logout().subscribe({ next: () => this.router.navigate(['/auth/login']) }); }
}
