import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { ButtonModule } from 'primeng/button';
import { CheckboxModule } from 'primeng/checkbox';
import { InputTextModule } from 'primeng/inputtext';
import { AuthService } from '../../core/services/auth.service';

@Component({ selector: 'app-login', standalone: true, imports: [ReactiveFormsModule, RouterLink, ButtonModule, CheckboxModule, InputTextModule], changeDetection: ChangeDetectionStrategy.OnPush, template: `<div class="login-page"><div class="login-heading"><div class="eyebrow">Espace professionnel</div><h1>Ravi de vous<br /><em>revoir.</em></h1><p>Connectez-vous pour retrouver vos projets, vos commandes et votre activité.</p></div><form [formGroup]="form" (ngSubmit)="submit()" class="login-form"><div class="field"><label for="email">Adresse email</label><input pInputText id="email" type="email" formControlName="email" placeholder="vous@entreprise.com" [class.ng-invalid]="form.controls.email.invalid && form.controls.email.touched" />@if (form.controls.email.invalid && form.controls.email.touched) { <small>Entrez une adresse email valide.</small> }</div><div class="field"><div class="field-label-row"><label for="password">Mot de passe</label><a routerLink="/auth/forgot-password">Mot de passe oublié ?</a></div><div class="password-field"><input pInputText id="password" [type]="showPassword() ? 'text' : 'password'" formControlName="password" placeholder="••••••••••••" /><button type="button" (click)="showPassword.set(!showPassword())" [attr.aria-label]="showPassword() ? 'Masquer' : 'Afficher'"><i class="pi" [class.pi-eye]="!showPassword()" [class.pi-eye-slash]="showPassword()"></i></button></div>@if (form.controls.password.invalid && form.controls.password.touched) { <small>Le mot de passe doit contenir au moins 6 caractères.</small> }</div><div class="remember-row"><p-checkbox formControlName="rememberMe" [binary]="true" inputId="remember"></p-checkbox><label for="remember">Se souvenir de moi</label></div>@if (error()) { <div class="form-error"><i class="pi pi-exclamation-circle"></i>{{ error() }}</div> }<p-button type="submit" label="Se connecter" icon="pi pi-arrow-right" iconPos="right" [loading]="loading()" [disabled]="form.invalid || loading()" styleClass="login-submit" /><div class="form-divider"><span>ou</span></div><button type="button" class="sso-button"><i class="pi pi-building"></i> Continuer avec SSO entreprise</button></form><p class="auth-switch">Vous n’avez pas encore de compte ? <a routerLink="/auth/register">Créer un compte</a></p><p class="demo-hint">Pour tester : créez d’abord un compte, puis utilisez la même adresse email et le même mot de passe.</p></div>` })
export class LoginComponent { private readonly fb = inject(FormBuilder); private readonly auth = inject(AuthService); private readonly router = inject(Router); showPassword = signal(false); loading = signal(false); error = signal(''); form = this.fb.nonNullable.group({ email: ['', [Validators.required, Validators.email]], password: ['', [Validators.required, Validators.minLength(6)]], rememberMe: [true] });
  submit(): void { if (this.form.invalid) { this.form.markAllAsTouched(); return; } this.loading.set(true); this.error.set(''); this.auth.login(this.form.getRawValue()).subscribe({ next: (response) => { localStorage.setItem('solar-access-token', response.accessToken); this.router.navigate(['/app']); }, error: (error: Error) => { this.error.set(error.message); this.loading.set(false); } }); }
}
