import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { ButtonModule } from 'primeng/button';
import { PasswordModule } from 'primeng/password';
import { AuthService } from '../../core/services/auth.service';

@Component({ selector: 'app-reset-password', standalone: true, imports: [ReactiveFormsModule, RouterLink, ButtonModule, PasswordModule], changeDetection: ChangeDetectionStrategy.OnPush, template: `<div class="login-page"><div class="login-heading"><div class="eyebrow">Nouveau mot de passe</div><h1>Sécurisez votre<br /><em>compte.</em></h1><p>Choisissez un nouveau mot de passe robuste pour votre espace SolaraTech.</p></div>@if (!done()) { <form class="login-form" [formGroup]="form" (ngSubmit)="submit()"><div class="field"><label for="new-password">Nouveau mot de passe</label><p-password inputId="new-password" formControlName="password" [toggleMask]="true" [feedback]="true" placeholder="8 caractères minimum" /></div><div class="field"><label for="confirm-password">Confirmer le mot de passe</label><p-password inputId="confirm-password" formControlName="confirmation" [toggleMask]="true" [feedback]="false" placeholder="Répétez votre mot de passe" /></div>@if (error()) { <div class="form-error"><i class="pi pi-exclamation-circle"></i>{{ error() }}</div> }<p-button type="submit" label="Enregistrer le nouveau mot de passe" icon="pi pi-check" iconPos="right" [loading]="loading()" [disabled]="form.invalid || form.value.password !== form.value.confirmation" styleClass="login-submit" /></form> } @else { <div class="success-panel"><div class="success-icon"><i class="pi pi-check"></i></div><h3>Mot de passe mis à jour</h3><p>Votre compte est sécurisé. Vous pouvez maintenant vous connecter.</p><p-button label="Se connecter" routerLink="/auth/login" [text]="true" /></div> }<p class="auth-switch"><a routerLink="/auth/login"><i class="pi pi-arrow-left"></i> Retour à la connexion</a></p></div>` })
export class ResetPasswordComponent { private readonly fb = inject(FormBuilder); private readonly auth = inject(AuthService); form = this.fb.nonNullable.group({ password: ['', [Validators.required, Validators.minLength(8)]], confirmation: ['', Validators.required] }); loading = signal(false); done = signal(false); error = signal(''); submit(): void { if (this.form.invalid || this.form.value.password !== this.form.value.confirmation) { this.form.markAllAsTouched(); return; } this.loading.set(true); this.auth.updatePassword(this.form.controls.password.value).subscribe({ next: () => { this.loading.set(false); this.done.set(true); }, error: (error: Error) => { this.loading.set(false); this.error.set(error.message); } }); } }
